// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Users, UsersData } from "./tables/Users.sol";
import { GameCodeToGameState } from "./tables/GameCodeToGameState.sol";
import { Orbs } from "./tables/Orbs.sol";
import { Balance } from "./tables/Balance.sol";
import { UserAccountMapping } from "./tables/UserAccountMapping.sol";
