// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Users, UsersData } from "./tables/Users.sol";
import { GameCodeToGameState, GameCodeToGameStateData } from "./tables/GameCodeToGameState.sol";
import { UserToOthersPositions } from "./tables/UserToOthersPositions.sol";
import { UserToOwnPositions } from "./tables/UserToOwnPositions.sol";
import { UserToSnakeDeque } from "./tables/UserToSnakeDeque.sol";
import { Balance } from "./tables/Balance.sol";
