// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBalanceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBalanceSystem {
  function startGame() external payable;

  function getContractBalance() external view returns (uint256);

  function getPlayerBalance(address player) external view returns (uint256);

  function getCurrentBalance() external view returns (uint256);

  function setGameFee(uint256 newFee) external;

  function deductBalance(address player, uint256 amount) external;

  function rechargeBalance(address player, uint256 amount) external;

  function payForGame(uint256 gf) external;
}
