// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Orb, UpdatePosition, Position } from "../../common.sol";

/**
 * @title IGameStateSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameStateSystem {
  function getOrbData() external view returns (Orb[] memory);

  function getUpdatePosition(address addr) external view returns (UpdatePosition memory _d);

  function stGame(string memory name) external;

  function endGame() external;

  function moveSnake(Position[] memory list) external;

  function adventureHeatbeat() external;

  function generateColor(int i) external view returns (string memory);

  function randomCoordinate(int i) external view returns (int32);

  function generateOrbSize(int i) external view returns (string memory);

  function generateRandom(int i) external view returns (uint256);
}
