// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position } from "../../common.sol";

/**
 * @title IGameStateSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameStateSystem {
  function endGame() external;

  function moveSnake(Position[] memory list) external;

  function adventureHeatbeat() external;
}
