// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position } from "../../common.sol";

/**
 * @title IHeatBeatSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IHeatBeatSystem {
  function moveSnake(uint32 gameCode, address player, Position memory newHeadPosition) external;

  function adventureHeatbeat() external;
}
