// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "../index.sol";

/**
 * @title IIncrementSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IIncrementSystem {
  function increment() external returns (uint32);

  function reStartScore() external;

  function move(uint32 direction) external;

  function getPositionData() external view returns (PositionData memory _p);

  function reStartGame() external;

  function myFunction() external;
}
