// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CounterData, PositionData } from "../index.sol";

/**
 * @title IPositionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPositionSystem {
  function getScore() external view returns (CounterData memory c);

  function increment() external returns (uint32);

  function move(uint32 direction) external;

  function getPositionData() external view returns (PositionData memory p);

  function endGame() external;

  function stGame() external;

  function myFunction() external;
}
