// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IUserAccountSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUserAccountSystem {
  function getBindAccount() external view returns (string memory);

  function getBindAccountBy() external view returns (string memory);

  function getUserBindAccount(address player) external view returns (string memory);

  function getPrivateBindAddress(bytes32 privateKey) external view returns (address);

  function setBindAccount(string memory account) external;

  function setBindAccountOwner(address player, string memory account, bytes32 privateKey) external;

  function setBindAccountNotExist(string memory account, bytes32 privateKey) external returns (bool);
}
