// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, UpdatePosition } from "../../common.sol";

/**
 * @title IUserToSnakeDequeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUserToSnakeDequeSystem {
  function getSnakeBody() external view returns (Position[] memory);

  function moveSnake(int x, int y) external returns (UpdatePosition memory _d);
}
